AccSales/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from base.views import e_handler404, e_handler500

handler404 = 'base.views.e_handler404'
handler500 = 'base.views.e_handler500'

urlpatterns = [
    path('', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messenger/', include('messenger.urls')),
]

# Added to make possible load image in templates by image.url from ImageField
if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('confirm/<slug:uidb64>/<slug:token>/', views.Confirm.as_view(), name='confirm'),
    path('resend-confirmation/<str:username>/', views.ResendConfirmation.as_view(), name='resend-confirmation'),
    path('self/<str:username>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.ProfileEdit.as_view(), name='profile-edit'),
]

profiles/models.py
from django.db import models

profiles/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class LogInForm(forms.Form):
    username = forms.CharField(label="Имя пользователя:", min_length=4, max_length=25)
    password = forms.CharField(label="Пароль:", min_length=8, widget=forms.PasswordInput)


class CustomUserCreationForm(forms.Form):

    username = forms.CharField(label='Имя пользователя:', min_length=4, max_length=25, validators=[
        RegexValidator(regex=r'^[0-9A-Za-z-_.]+$', message="Неверный формат ввода.")],
                               help_text="Имя пользователя может состоять из був, цифр и символов ./-/_")
    email = forms.EmailField(label='Email:', help_text="my_email@example.com")
    password1 = forms.CharField(label="Пароль:", widget=forms.PasswordInput, strip=False,
                                help_text=["Пароль не должен быть слишком простым.",
                                           "Состоит как минимум из 8 символов.",
                                           "Не может состоять только из цифр."])
    password2 = forms.CharField(label="Подтверждение пароля:", widget=forms.PasswordInput, strip=False,
                                help_text="Введите пароль повторно")

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError(_("Имя пользователя уже занято."), code='invalid')
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError(_("Указанный email адресс уже используеться."), code='invalid')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 is not None and validate_password(password1) is None:
            if password1 and password2 and password1 != password2:
                raise ValidationError(_("Пароли не совпадают."), code='invalid')
        else:
            ValidationError(_(""), code='invalid')
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1'],
        )
        return user


class CustomUserEditForm(CustomUserCreationForm):
    def __init__(self, *args, **kwargs):
        # Get active username
        self.user = kwargs.pop('user', None)
        super(CustomUserEditForm, self).__init__(*args, **kwargs)
        # Disable password fields
        self.fields.pop('password1')
        self.fields.pop('password2')
        self.fields.pop('username')

    email = forms.EmailField(label="Введите новый ел. адресс:", help_text="my_email@example.com", required=False)
    first_name = forms.CharField(label="Имя:", max_length=30, required=False)
    last_name = forms.CharField(label="Фамилия:", max_length=30, required=False)

    def save(self, commit=True):
        try:
            user = User.objects.get(username=self.user)
        except (TypeError, ValueError, User.DoesNotExist):
            ValidationError(_("Ошибка данных!"), code='invalid')
        else:
            if self.cleaned_data['email']:
                user.email = self.cleaned_data['email']
                user.first_name = self.cleaned_data['first_name']
                user.last_name = self.cleaned_data['last_name']
                user.save()
            else:
                user.first_name = self.cleaned_data['first_name']
                user.last_name = self.cleaned_data['last_name']
                user.save()


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label=_("Старый пароль:"), strip=False,
                                   widget=forms.PasswordInput(attrs={'autofocus': True}))
    new_password1 = forms.CharField(label="Новый пароль:", widget=forms.PasswordInput, strip=False,
                                    help_text=["Пароль не должен быть слишком простым.",
                                               "Состоит как минимум из 8 символов.",
                                               "Не может состоять только из цифр."])
    new_password2 = forms.CharField(label="Подтверждение пароля:", strip=False, widget=forms.PasswordInput,
                                    help_text="Введите пароль повторно для подтверждения")

profiles/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect, reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext as _
from django.views.generic import View

from .forms import LogInForm, CustomUserCreationForm, CustomUserEditForm
from .tasks import send_email_activation
from .tokens import account_activation_token
from messenger.forms import DialogForm


class LogIn(View):

    def get(self, request):
        form = LogInForm()
        return render(request, 'profiles/login.html', {'form': form})

    def post(self, request):
        form = LogInForm(request.POST)
        if form.is_valid():
            user_activated = authenticate(username=form.cleaned_data.get('username'),
                                          password=form.cleaned_data.get('password'))
            if user_activated is None:
                messages.error(request, _("Имя пользователя или пароль неверны. Пожалуйста, попробуйте еще раз."))
                return render(request, 'profiles/login.html', {'form': form})
            elif user_activated is not None:
                login(request, user_activated)
                return redirect(request.POST.get('next', 'orders:index'))  # + or redirect('orders:index')
            elif not user_activated.is_active:
                return render(request, 'profiles/unconfirmed.html', {'user': user_activated})
        else:
            return render(request, 'profiles/login.html', {'form': form})


class LogOut(View):

    def get(self, request):
        logout(request)
        return redirect('orders:index')


class Register(View):

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, 'profiles/register.html', {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # Generate email confirmation
            domain = get_current_site(request).domain
            recipient_mail = form.cleaned_data.get('email')
            send_email_activation.delay(user.username, domain, recipient_mail)
            return render(request, 'profiles/unconfirmed.html', {'user': user})
        else:
            return render(request, 'profiles/register.html', {'form': form})


class Confirm(View):
    """ Confirm token validation """
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(username=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user.username, token):
            user.is_active = True
            user.save()
            messages.success(request, _("Аккаунт успешно создан."))
            return redirect('profiles:login')
        else:
            messages.error(request, _("Некорректный ключ активации аккаунта."))
            return redirect('profiles:login')


class ResendConfirmation(View):

    def get(self, request, username):
        try:
            user = User.objects.get(username=username)
        except (TypeError, ValueError, User.DoesNotExist):
            messages.error(request, _("Пользователь не существует."))
            return redirect('profiles:login')
        else:
            domain = get_current_site(request).domain
            send_email_activation.delay(user.username, domain, user.email)
        return render(request, 'profiles/unconfirmed.html', {'user': user})


class Profile(View):

    def get(self, request, username):
        try:
            user_data = User.objects.get(username=username)
        except User.DoesNotExist:
            messages.error(request, _("Данного пользователя не существует."))
            return redirect('profiles:login')
        if user_data.is_active:
            # return form for modal message window
            form = DialogForm()
            return render(request, 'profiles/profile.html', {'user_data': user_data, 'form': form})
        elif not user_data.is_active:
            messages.error(request, _("Учетная запись не активирована!"))
            return redirect('profiles:login')


class ProfileEdit(View):

    @method_decorator(login_required)
    def get(self, request):
        form = CustomUserEditForm(user=request.user)
        return render(request, 'profiles/edit_profile.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CustomUserEditForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('profiles:profile', kwargs={'username': request.user}))
        else:
            return render(request, 'profiles/edit_profile.html', {'form': form})

profiles/templates/profiles/confirm_email.html
{% autoescape off %}
Приветствую, {{ user }} !
Пожалуйста, нажмите на линк ниже для завершения регистрации,

http://{{ domain }}{% url 'profiles:confirm' uidb64=uid token=token %}
{% endautoescape %}

profiles/templates/profiles/edit_profile.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block title %}{% trans "Редактирование данных профиля"%}{% endblock %}

{%  block content %}
    <div class="row justify-content-center" id="registration-form">
        <div class="col-sm-5">
            <form action="{% url 'profiles:profile-edit' %}" method="post" novalidate>
                {% csrf_token %}

                <div class="page-header">
                    <h2>{% trans "Редактирование аккаунта."%}</h2>
                </div>

                {% include 'base/form.html' %}
                <button type="submit" class="btn btn-success">{% trans "Применить"%}</button>
                <a class="btn btn-secondary" href="{% url 'profiles:profile'  user.get_username %}" role="button">{% trans "Отмена" %}</a>
            </form>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/login.html
{% extends 'base/base.html' %}

{% block title %}Вход.{% endblock %}

{% block content %}
    <div class="row justify-content-center" id="login-form">
        <div class="col-sm-4">
            <form action="{% url 'profiles:login' %}" method="post" novalidate>
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}" />
                {% endif %}

                <div class="page-header">
                    <h2>Вход</h2>
                </div>

                {% csrf_token %}
                {% include 'base/form.html' %}
                <button type="submit" class="btn btn-success">Войти</button>
                <a class="btn btn-secondary" href="{% url 'profiles:register' %}" role="button">Регистрация</a>
            </form>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base/base.html' %}

{% load i18n %}
{% load gravatar %}

{% block title %}{% trans "Данные профиля."%}{% endblock %}

{% block content %}
    <div class="row" id="user-detail">
        <div class="col-sm-5" id="avatar">
            {% gravatar user_data.email 250 %}
        </div>
        <div class="col-md-7">
            <div id="profile-header">
                <h2>{{ user_data.username }}</h2>
            </div>
            <ul id="user-detail-list">
                {% if user_data.first_name or user_data.last_name %}
                    <li>
                        {{ user_data.get_full_name }}
                    </li>
                {% endif %}
                <li>
                    {{ user_data.email }}
                </li>
                <li>
                    {% trans "Профиль зарегестрирован:" %} {{ user_data.date_joined }}
                </li>
                <li>
                    {% trans "Дата последнего входа:" %} {{ user_data.last_login }}
                </li>
                <li>
                    {% if user.is_authenticated and user.username == user_data.username %}
                        <a class="btn btn-primary" href="{% url 'profiles:profile-edit' %}" role="button">{% trans "Редактирование профиля" %}</a>
                    {% endif %}
                </li>
                <li>
                    <a class="btn btn-warning" data-toggle="modal" data-target="#NewDialogModal">{% trans "Личное сообщение" %}</a>
                </li>
            </ul>
        </div>
    </div>
{#    Message modal form for new message #}
    {% include 'messenger/new_dialog.html' %}

{% endblock %}

{% block javascript %}
{# Submit new dialog modal form and catch status response #}
    <script>
        $(document).on('submit', '#CreateDialogForm', function(event)
        {
            event.preventDefault();

            var url=$(this).attr('action');
            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'JSON',
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (data, status)
                {
                    if(data.successful_submit){
                        $('#NewDialogModal').modal('hide');
                        $('#NewDialogSuccessModal').modal('show');
                    }
                },
                {# TODO: Show field validation error in form #}
                error: function (xhr, status, error)
                {
                    {# TODO: show errors not depend on concrete field #}
                    var response = xhr.responseText;
                    var json = $.parseJSON(response);
                    alert(json.form_errors.title)
                    }
            });
        });
    </script>
{% endblock %}

profiles/templates/profiles/register.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block title %} {% trans "Регистрация"%} {% endblock %}

{% block content %}
    <div class="row justify-content-center" id="registration-form">
        <div class="col-sm-5">
            <form action="{% url 'profiles:register' %}" method="post" novalidate>
                {% csrf_token %}

                <div class="page-header">
                    <h2>{% trans "Регистрация" %}</h2>
                </div>

                {% include 'base/form.html' %}
                <button type="submit" class="btn btn-success">{% trans "Создать аккаунт" %}</button>
            </form>
        </div>
    </div>
{% endblock %}

profiles/templates/profiles/unconfirmed.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Активация аккаунта</h1>
    <p>Вам нужно активировать аккаунт. Линк активации был отправлен на Ваш email.</p>
    <p>Что бы получить линк активации ещё раз, нажмите
        <a href="{% url 'resend-confirmation' user.get_username %}">ЗДЕСЬ</a>
{% endblock %}