AccSales/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from base.views import e_handler404, e_handler500

handler404 = 'base.views.e_handler404'
handler500 = 'base.views.e_handler500'

urlpatterns = [
    path('', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messenger/', include('messenger.urls')),
]

# Added to make possible load image in templates by image.url from ImageField
if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

messenger/urls.py
from django.urls import path

from . import views

app_name = 'messenger'

urlpatterns = [
    path('dialogs/', views.DialogsView.as_view(), name='dialogs'),
    path('dialogs/create/<int:user_id>/', views.DialogCreateView.as_view(), name='dialog-create'),
    path('dialogs/<int:dialog_id>/', views.MessagesView.as_view(), name='messages'),
    path('dialogs/message/<int:message_id>/', views.MessageUpdate.as_view(), name='message-update'),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('confirm/<slug:uidb64>/<slug:token>/', views.Confirm.as_view(), name='confirm'),
    path('resend-confirmation/<str:username>/', views.ResendConfirmation.as_view(), name='resend-confirmation'),
    path('self/<str:username>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.ProfileEdit.as_view(), name='profile-edit'),
]

messenger/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from base.models import BaseModel


class DialogManager(models.Manager):
    use_for_related_fields = True
    # Метод принимает пользователя, для которого должна производиться выборка
    # Если пользователь не добавлен, то будет возвращены все диалоги,
    # в которых хотя бы одно сообщение не прочитано

    def unread(self, user=None):
        qs = self.get_queryset().exclude(last_message__isnull=True).filter(last_message__is_read=False)
        return qs.exclude(last_message__author=user) if user else qs


class Dialog(BaseModel):
    title = models.CharField(_('Тема'), max_length=64, unique=True)
    members = models.ManyToManyField(User, verbose_name=_("Участник"))
    # Внешний ключ на последнее сообщение,
    # Также необходимо добавить related_name, имя через которое будет ассоциироваться выборка данного сообщения из бд
    last_message = models.ForeignKey('Message', related_name='last_message', null=True, blank=True,
                                     on_delete=models.SET_NULL)
    objects = DialogManager()

    class Meta:
        ordering = ['-updated']

    def get_absolute_url(self):
        return reverse('messenger:messages', args=[str(self.id)])


class Message(BaseModel):
    dialog = models.ForeignKey(Dialog, verbose_name=_("Диалог"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    text = models.TextField(_("Сообщение"))
    is_read = models.BooleanField(_('Прочитано'), default=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('messenger:messages', args=[str(self.id)])

messenger/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.models import ModelForm
from django.utils.translation import gettext as _

from .models import Dialog, Message


class DialogForm(forms.Form):
    title = forms.CharField(label="Тема:", max_length=64)
    text = forms.CharField(widget=forms.Textarea, required=True)

    def __init__(self, *args, **kwargs):
        self.user_from = kwargs.pop('user_from', None)
        self.user_to = kwargs.pop('user_to', None)
        super(DialogForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title'].lower()
        dialog = Dialog.objects.filter(title=title)
        if dialog.count():
            raise ValidationError(_("Диалог с таким названием уже существует."), code='invalid')
        return title

    def save(self, commit=True):
        title = self.cleaned_data['title'].lower()
        text = self.cleaned_data['text']
        members = (self.user_from, self.user_to)
        dialog = Dialog.objects.create(title=title)
        dialog.members.add(*members)
        Message.objects.create(dialog_id=dialog.id, author_id=members[0], text=text)


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        labels = {'text': ""}

messenger/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import View, UpdateView

from .forms import MessageForm, DialogForm
from .models import Dialog, Message


class DialogsView(View):

    @method_decorator(login_required)
    def get(self, request):
        dialogs = Dialog.objects.filter(members__in=[request.user.id])
        return render(request, 'messenger/dialogs.html', {'dialogs': dialogs})


class DialogCreateView(View):

    @method_decorator(login_required)
    def post(self, request, user_id):
        form = DialogForm(data=request.POST, user_from=request.user.id, user_to=user_id)
        if form.is_valid():
            form.save()
            return JsonResponse({'successful_submit': True})
        else:
            return JsonResponse({'form_errors': form.errors}, status=422)


class MessagesView(View):

    @method_decorator(login_required)
    def get(self, request, dialog_id):
        try:
            dialog = Dialog.objects.get(id=dialog_id)
            if request.user in dialog.members.all():
                dialog.message_set.filter(is_read=False).exclude(author=request.user).update(is_read=True)
            else:
                dialog = None
        except Dialog.DoesNotExist:
            dialog = None

        return render(request, 'messenger/messages.html', {'user_profile': request.user,
                                                           'dialog': dialog,
                                                           'form': MessageForm()
                                                           })

    @method_decorator(login_required)
    def post(self, request, dialog_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.dialog_id = dialog_id
            message.author = request.user
            message.save()
        return redirect(reverse('messenger:messages', kwargs={'dialog_id': dialog_id}))


class MessageUpdate(UpdateView):
    model = Message
    fields = ['text']
    pk_url_kwarg = 'message_id'
    template_name = 'messenger/edit_message.html'
    context_object_name = 'dialog'

    """ We can do not use 'success_url' variable and 'form_valid' method. Instead of that CreateView and UpdateView
    use 'get_absolute_url' method from model object (if exist).
    """

    # def form_valid(self, form):
    #     message = form.save()
    #     return redirect('messenger:messages', dialog_id=message.dialog_id)

messenger/templates/messenger/dialogs.html
{% extends 'base/base.html' %}

{% load tz %}
{% load i18n %}
{% load humanize %}
{% load messenger_extras %}

{% block title %}{% trans "Диалоги." %}{% endblock %}

{% block content %}

    <div class="row justify-content-center">
        <div class="col-lg">
            {% if dialogs.count == 0 %}
            <h3>{% trans "Нет ни одного начатого диалога." %}</h3>
            {% else %}
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{% trans "Тема" %}</th>
                            <th scope="col">{% trans "Пользователь" %}</th>
                            <th scope="col">{% trans "Дата" %}</th>
                        </tr>
                    </thead>
                    {% for dialog in dialogs %}
                        {% if dialog.message_set.count != 0 %}
                            {% with last_message=dialog.message_set.last %}
                                {% get_companion user dialog as companion %}
                                    <tbody>
                                        <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <td>
                                                <a href="{{ dialog.get_absolute_url }}">
{#                                                    TODO: Check if is_read work #}
                                                    {% if companion == last_message.author and not last_message.is_read %}
                                                        <b>{{ dialog.title }}</b>
                                                    {% else %}
                                                        {{ dialog.title }}
                                                    {% endif %}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'profiles:profile' last_message.author.username %}">{{ last_message.author }}</a>
                                            </td>
                                            <td>{{ last_message.created|naturaltime }}</td>
                                        </tr>
                                        </tbody>
                            {% endwith %}
                        {% endif %}
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>

{% endblock %}

messenger/templates/messenger/edit_message.html
{% extends 'base/base.html' %}

{% load i18n %}

{% block title %} {% trans "Редактирование сообщения" %} {% endblock %}

{% block content %}
    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'base/form.html' %}
        <button type="submit" class="btn btn-success">{% trans "Сохранить изменения" %}</button>
        <a href="{% url 'messenger:messages' dialog.id %}" class="btn btn-outline-secondary" role="button">{% trans "Отмена" %}</a>
  </form>
{% endblock %}

messenger/templates/messenger/messages.html
{% extends 'base/base.html' %}

{% load tz %}
{% load i18n %}
{% load humanize %}
{% load gravatar %}
{% load messenger_extras %}

{% block title %}Сообщения.{% endblock %}

{% block content %}
        {% if dialog %}
            {% for message in dialog.message_set.all %}
                {% with first_message=dialog.message_set.first %}
                <div id="{{ message.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if message.pk == first_message.pk %}border-primary{% endif %}">
                    {% if message.pk == first_message.pk %}
                        <div class="card-header text-white bg-primary py-2 px-3">{{ dialog.title }}</div>
                    {% endif %}
                    <div class="card-body p-3">
                        <div class="row">
                            <div class="col-2">
                                {% gravatar  message.author.email 100 %}<br>
                            </div>
                            <div class="col-10">
                                <div class="row mb-3">
                                    <div class="col-9">
                                        <p>{{ message.text }}</p>
                                    </div>
                                    <div class="col-3 text-right">
                                        <small class="text-muted">{{ message.created|naturaltime }}</small>
                                    </div>
                                </div>
                                {% if message.author == user %}
                                    <div class="mt-3">
                                        <a href="{% url 'messenger:message-update' message.id %}" class="btn btn-warning btn-sm" role="button">Edit</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endwith %}
            {% endfor %}
        {% endif %}
        <div class="row justify-content-center" id="message-form">
            <div class="col-lg">
                <form action="{% url 'messenger:messages' dialog.pk %}" method="post" novalidate>
                    {% csrf_token %}

                    {% include 'base/form.html' %}
                    <button type="submit" class="btn btn-success">{% trans "Отправить" %}</button>
                </form>
            </div>
        </div>
{% endblock %}

messenger/templates/messenger/new_dialog.html
{% load i18n %}

{#{% url 'users:profile' message_item.author.username as the_user_url%}#}
{##}
{#<div class="list-group-item {% if not message_item.is_readed %}unread{% endif %}">#}
{#    <a href="{{ the_user_url }}"><img class="avatar-comment" src="{{ message_item.author.userprofile.get_avatar }}"></a>#}
{#    <div class="reply-body">#}
{#        <ul class="list-inline">#}
{#            <li class="drop-left-padding">#}
{#                <strong class="list-group-item-heading"><a href="{{ the_user_url }}">{{ message_item.author.username }}</a></strong>#}
{#            </li>#}
{#            <li class="pull-right text-muted"><small>{{ message_item.pub_date|utc }}</small></li>#}
{#        </ul>#}
{#        <div>{{ message_item.message|safe }}</div>#}
{#    </div>#}
{#</div>#}

<!-- Modal create message form -->
<div class="modal fade" id="NewDialogModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl" role="document" aria-labelledby="NewDialogModalLabel" aria-hidden="true">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{% trans "Новое сообщение" %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="CreateDialogForm" action="{% url 'messenger:dialog-create' user_data.id %}" method="post" novalidate>
                    {% csrf_token %}
                    {% include 'base/form.html' %}

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Отмена" %}</button>
                        <button type="submit" class="btn btn-primary">{% trans "Отправить" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="NewDialogSuccessModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document" aria-labelledby="NewDialogSuccessModalLabel" aria-hidden="true">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p>{% trans "Сообщение отправлено."%}</p>
            </div>
        </div>
    </div>
</div>