AccSales/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from base.views import e_handler404, e_handler500

handler404 = 'base.views.e_handler404'
handler500 = 'base.views.e_handler500'

urlpatterns = [
    path('', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messenger/', include('messenger.urls')),
]

# Added to make possible load image in templates by image.url from ImageField
if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

base/models.py
from django.db import models
from django.utils.translation import ugettext as _


class BaseModel(models.Model):
    class Meta:
        abstract = True

    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name=_('Created'))
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name=_('Updated'))

    objects = models.Manager()

base/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _


def e_handler404(request, exception):
    context = {'message': _("По указаной ссылке ничего не найдено.")}
    response = render(request, 'base/404.html', context=context, status=404)
    return response


def e_handler500(request):
    context = {'message': _("Внутренняя ошибка сервера.")}
    response = render(request, 'base/500.html', context=context, status=500)
    return response


def csrf_failure(request, reason=""):
    context = {'message': _("Проверка соответсвия CSRF провалена.")}
    return render(request, 'base/403.html', context=context, status=403)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head %}
        <title>{% block title %}Base template{% endblock %}</title>
    {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block stylesheet %}{% endblock %}
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home:index' %}">AccSales</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <!-- Authentication -->
            <ul class="nav justify-content ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" style="text-decoration: none;">
                            <b class="nav-item caret">Profile</b>
                        </a>
                        <ul class="nav-item dropdown-menu">
                            <li><a class="nav-link" href="{% url 'profiles:user_logout' %}">Exit</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'profiles:user_login' %}">LogIn</a></li>
                {% endif %}
            </ul>
        </div>
    </nav> <!-- End navbar -->

    {% block content %}
        <div class="container">
        <!-- Content here -->
            {% block page %}
            {% endblock %}
        </div> <!-- /.container -->
    {% endblock content %}

    {#  Messages  #}
    {% if messages %}
        <div class="row justify-content-center" id="system-message">
            <div class="col-sm-6">
                <ul class="help-list">
                    {% for message in messages %}
                        {% if message.level_tag == 'info' %}
                            <div class="alert alert-warning" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                </button>
                                </li>
                            </div>
                        {% elif message.level_tag == 'success'%}
                            <div class="alert alert-success" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </li>
                            </div>
                        {% elif message.level_tag == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </li>
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
</body>
</html>