AccSales/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from base.views import e_handler404, e_handler500

handler404 = 'base.views.e_handler404'
handler500 = 'base.views.e_handler500'

urlpatterns = [
    path('', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messenger/', include('messenger.urls')),
]

# Added to make possible load image in templates by image.url from ImageField
if settings.DEBUG is True:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
]

messenger/urls.py
from django.urls import path

from . import views

app_name = 'messenger'

urlpatterns = [
    path('dialogs/', views.DialogsView.as_view(), name='dialogs'),
    path('dialogs/create/<int:user_id>/', views.DialogCreateView.as_view(), name='dialog-create'),
    path('dialogs/<int:dialog_id>/', views.MessagesView.as_view(), name='messages'),
    path('dialogs/message/<int:message_id>/', views.MessageUpdate.as_view(), name='message-update'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'
urlpatterns = [
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('confirm/<slug:uidb64>/<slug:token>/', views.Confirm.as_view(), name='confirm'),
    path('resend-confirmation/<str:username>/', views.ResendConfirmation.as_view(), name='resend-confirmation'),
    path('self/<str:username>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.ProfileEdit.as_view(), name='profile-edit'),
]

base/models.py
from django.db import models
from django.utils.translation import ugettext as _


class BaseModel(models.Model):
    class Meta:
        abstract = True

    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name=_('Created'))
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name=_('Updated'))

    objects = models.Manager()

base/views.py
from django.shortcuts import render
from django.utils.translation import gettext as _


def e_handler404(request, exception):
    context = {'message': _("По указаной ссылке ничего не найдено.")}
    response = render(request, 'base/404.html', context=context, status=404)
    return response


def e_handler500(request):
    context = {'message': _("Внутренняя ошибка сервера.")}
    response = render(request, 'base/500.html', context=context, status=500)
    return response


def csrf_failure(request, reason=""):
    context = {'message': _("Проверка соответсвия CSRF провалена.")}
    return render(request, 'base/403.html', context=context, status=403)

base/templates/base/base.html
{% load i18n %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block head %}
        <title>{% block title %}Base template{% endblock %}</title>
    {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block stylesheet %}{% endblock %}
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'orders:index' %}">AccSales</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <!-- Authentication -->
            <ul class="nav justify-content ml-auto">
                {% if user.is_authenticated %}
                    <a href="{% url 'messenger:dialogs' %}">
{#                        <svg width="50" height="50" viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd">#}
{#                            <path d="M24 21h-24v-18h24v18zm-23-16.477v15.477h22v-15.477l-10.999 10-11.001-10zm21.089-.523h-20.176l10.088 9.171 10.088-9.171z"/></svg>#}
                        <button type="button" class="btn btn-primary">
                            {% trans "Сообщения" %} <span class="badge badge-light">{{unread_messages_count}}</span>
                            <span class="sr-only">unread messages</span>
                        </button>
                    </a>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" style="text-decoration: none;">
                            <b class="nav-item caret">{{ user.username }}</b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profiles:profile' user.get_username %}">{% trans "Личные данные" %}</a></li>
                            <li><a class="nav-link" href="{% url 'profiles:logout' %}">{% trans "Выход" %}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'profiles:login' %}">{% trans "Вход" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav> <!-- End navbar -->

    <div class="container">{% block content %}<!-- Content here -->{% endblock content %}</div>

    {#  Messages  #}
    {% if messages %}
        <div class="row justify-content-center" id="system-message">
            <div class="col-sm-6">
                <ul class="help-list">
                    {% for message in messages %}
                        {% if message.level_tag == 'info' %}
                            <div class="alert alert-warning" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                </button>
                                </li>
                            </div>
                        {% elif message.level_tag == 'success'%}
                            <div class="alert alert-success" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </li>
                            </div>
                        {% elif message.level_tag == 'error' %}
                            <div class="alert alert-danger" role="alert">
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <strong>{{ message }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </li>
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block javascript %}{% endblock %}
</body>
</html>

base/templates/base/form.html
{% load widget_tweaks %}

{% block stylesheet %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}


{% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script>
        var simplemde = new SimpleMDE();
    </script>
{% endblock %}